### ISSUE TITLE
Can't connect to archipelago.gg:PORT games

### ISSUE THREAD

**Issue by jacobmix** [LegendaryLinux/APSpectator#3]
Seems to connect fine when self hosting. But doesn't connect at all when using the site?
Not sure if this is still updated. See some stuff is out of date like amount of color classes for important, ect items. (Saw a pull request for it tho)

**Comment by jacobmix** [comment]
Easy fix. Just change ws to wss.
`serverSocket = new WebSocket(`ws://${serverAddress}`);`
`serverSocket = new WebSocket(`wss://${serverAddress}`);`

**Comment by jacobmix** [comment]
Made a pull request for it. Tho be free to make any changes yourself, and not even merge this as i litterally just added an s.
https://github.com/LegendaryLinux/APSpectator/pull/4

**Comment by jacobmix** [comment]
Ah, if it isn't just ws it won't work for locally hosted games. Might need more code than adding a single s.

**Comment by KonoTyran** [comment]
Most web browsers will not connect to a secure websocket from a non secure page, and vice versa, For security reasons. So the main attempt at using this as a local browser source just wont work, unless this gets hosted on a page somewhere that can properly support an https connection.

**Comment by KonoTyran** [comment]
So a "more code" won't fix that issue.

**Comment by jacobmix** [comment]
Well, seems to work for me with the changes in the pull. But maybe i just haven't tested enough.
Ah, yeah. Browser source still doesn't work with the site. But if run through a normal browser it works.
